# Generated by Django 3.2.12 on 2022-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('iamge', models.ImageField(upload_to='./images/')),
                ('process_state', models.CharField(choices=[('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('VALID', 'Valid'), ('FRAUD', 'Fraud')], default='PENDING', max_length=10)),
            ],
        ),
    ]
