# Generated by Django 3.2.12 on 2022-04-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrdocument', '0002_auto_20220401_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdocument',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
